### PR TITLE
enarx.ks: add user "puiterwijk"

### PR DESCRIPTION
**Pull request by puiterwijk**

### CODE REVIEW

**Review by lkatalin — APPROVED** [review]

**Comment by lkatalin** [comment]
FYI I suggested this to @puiterwijk , as he wants to do some development work and does not currently have the right hardware.

**Comment by npmccallum** [comment]
@puiterwijk Welcome! Can I get some background for this PR?

**Comment by puiterwijk** [comment]
@npmccallum Hi! Sure, @lkatalin suggested I could request access to these systems as I was trying to develop an application I'd like to run in an enclave, and I do not have any hardware yet with SGX2 or SEV.

**Comment by npmccallum** [comment]
@puiterwijk I can approve this if you rebase it. Otherwise, please close the PR.

**Comment by puiterwijk** [comment]
@npmccallum rebased, thanks.

**Review by npmccallum — APPROVED** [review]

**Review by connorkuehl — APPROVED** [review]

**Pull request merged**
